services:
  - type: web
    name: agricultural-monitoring-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app -k gthread --threads 4 --timeout 180
    envVars:
      - key: DEMO_MODE
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.0"